-- =====================================================================
-- MECHmetrIQ — Raw Material Marketplace starter catalogue (GENERATED)
-- Source: supabase/scripts/gen_rm_catalog_seed.py — edit there, re-run.
-- Rates are INDICATIVE placeholders (₹/kg excl. GST); update them in
-- Admin → Raw Material Marketplace → Rate card before go-live.
-- Idempotent: re-running updates catalogue text but never overwrites
-- rates that already exist.
-- =====================================================================

insert into public.rm_shapes (slug, name, family, formula, sell_by, hsn_key, rate_premium_pct,
  std_lengths, std_sheet_sizes, dims, description, sort_order) values
('round-bar', 'Round Bar', 'bar', 'round_bar', 'piece', 'bar', 0, array[3000, 6000]::numeric[], '[]'::jsonb, '[{"key":"d","label":"Diameter","unit":"mm","std":[6,8,10,12,16,20,25,32,40,50,63,75,100,125,150,200],"min":3,"max":600}]'::jsonb, 'Solid bright or black round bars for turning, shafts, pins and general machining.', 1),
('square-bar', 'Square Bar', 'bar', 'square_bar', 'piece', 'bar', 3, array[3000, 6000]::numeric[], '[]'::jsonb, '[{"key":"a","label":"Side","unit":"mm","std":[10,12,16,20,25,32,40,50,63,75,100],"min":5,"max":300}]'::jsonb, 'Solid square bars for fixtures, keys, frames and milled parts.', 2),
('hex-bar', 'Hex Bar', 'bar', 'hex_bar', 'piece', 'bar', 6, array[3000, 6000]::numeric[], '[]'::jsonb, '[{"key":"af","label":"Across flats","unit":"mm","std":[8,10,12,13,17,19,22,24,27,30,36,41,46,50],"min":5,"max":150}]'::jsonb, 'Hexagonal bars (sized across flats) for nuts, fittings and turned components.', 3),
('flat-bar', 'Flat Bar', 'bar', 'flat_bar', 'piece', 'bar', 2, array[3000, 6000]::numeric[], '[]'::jsonb, '[{"key":"w","label":"Width","unit":"mm","std":[12,16,20,25,32,40,50,63,75,100,125,150],"min":5,"max":600},{"key":"t","label":"Thickness","unit":"mm","std":[3,5,6,8,10,12,16,20,25,32,40,50],"min":1,"max":200}]'::jsonb, 'Rectangular flat bars for brackets, base plates, wear strips and fabrication.', 4),
('sheet', 'Sheet (0.3–6 mm)', 'flat', 'sheet', 'piece', 'flat', 5, '{}'::numeric[], '[[1000,2000],[1250,2500],[1500,3000]]'::jsonb, '[{"key":"t","label":"Thickness","unit":"mm","std":[0.5,0.8,1,1.2,1.5,2,2.5,3,4,5,6],"min":0.3,"max":6},{"key":"w","label":"Width","unit":"mm","std":[1000,1250,1500],"min":50,"max":2000},{"key":"l","label":"Length","unit":"mm","std":[2000,2500,3000],"min":50,"max":6000}]'::jsonb, 'Cold- or hot-rolled sheets up to 6 mm, full size or cut to your width × length.', 5),
('plate', 'Plate (above 6 mm)', 'flat', 'sheet', 'piece', 'flat', 0, '{}'::numeric[], '[[1250,2500],[1500,3000],[2000,6000]]'::jsonb, '[{"key":"t","label":"Thickness","unit":"mm","std":[8,10,12,16,20,25,32,40,50,63,80,100],"min":6.01,"max":300},{"key":"w","label":"Width","unit":"mm","std":[1250,1500,2000],"min":50,"max":2500},{"key":"l","label":"Length","unit":"mm","std":[2500,3000,6000],"min":50,"max":12000}]'::jsonb, 'Hot-rolled plates over 6 mm for base frames, dies, flanges and structural work.', 6),
('chequered-plate', 'Chequered Plate', 'flat', 'sheet', 'piece', 'flat', 4, '{}'::numeric[], '[[1250,2500],[1500,6000]]'::jsonb, '[{"key":"t","label":"Base thickness","unit":"mm","std":[3,4,5,6,8,10],"min":2,"max":12},{"key":"w","label":"Width","unit":"mm","std":[1250,1500],"min":50,"max":2000},{"key":"l","label":"Length","unit":"mm","std":[2500,6000],"min":50,"max":6300}]'::jsonb, 'Anti-slip raised-pattern plates for flooring, stairs and platforms. Weight is on base thickness; the raised pattern adds a little.', 7),
('perforated-sheet', 'Perforated Sheet', 'flat', 'perforated', 'piece', 'flat', 25, '{}'::numeric[], '[[1000,2000],[1250,2500]]'::jsonb, '[{"key":"t","label":"Thickness","unit":"mm","std":[0.8,1,1.2,1.5,2,3],"min":0.5,"max":6},{"key":"w","label":"Width","unit":"mm","std":[1000,1250],"min":50,"max":1500},{"key":"l","label":"Length","unit":"mm","std":[2000,2500],"min":50,"max":3000},{"key":"open","label":"Open area","unit":"%","std":[23,33,40,51],"min":5,"max":70}]'::jsonb, 'Round-hole perforated sheets for guards, screens, filters and façades.', 8),
('coil', 'Coil / Strip', 'flat', 'coil', 'kg', 'flat', 0, '{}'::numeric[], '[]'::jsonb, '[{"key":"t","label":"Thickness","unit":"mm","std":[0.3,0.5,0.8,1,1.2,1.5,2,3],"min":0.1,"max":6},{"key":"w","label":"Width","unit":"mm","std":[50,100,150,300,600,1000,1250,1500],"min":10,"max":2000}]'::jsonb, 'Coils and slit strip sold by weight — tell us thickness and width.', 9),
('seamless-pipe', 'Seamless Pipe / Tube', 'pipe', 'round_tube', 'piece', 'seamless', 20, array[6000]::numeric[], '[]'::jsonb, '[{"key":"od","label":"Outer diameter","unit":"mm","std":[6,10,12,16,21.3,26.7,33.4,42.2,48.3,60.3,88.9,114.3,168.3],"min":3,"max":610},{"key":"t","label":"Wall thickness","unit":"mm","std":[1,1.5,2,2.77,3.38,3.91,5.54,7.11],"min":0.5,"max":60}]'::jsonb, 'Seamless pipes and tubes for pressure, hydraulic and high-temperature service.', 10),
('erw-pipe', 'ERW / Welded Pipe', 'pipe', 'round_tube', 'piece', 'welded', 8, array[6000]::numeric[], '[]'::jsonb, '[{"key":"od","label":"Outer diameter","unit":"mm","std":[12.7,15.9,19.05,21.3,25.4,26.9,33.7,38.1,42.4,48.3,50.8,60.3,76.1,88.9,114.3],"min":6,"max":610},{"key":"t","label":"Wall thickness","unit":"mm","std":[0.8,1,1.2,1.6,2,2.6,2.9,3.2,3.6,4.5],"min":0.5,"max":12}]'::jsonb, 'Welded (ERW) round pipes for structures, railings, furniture and utility lines.', 11),
('square-hollow', 'Square Hollow Section', 'pipe', 'square_tube', 'piece', 'welded', 8, array[6000]::numeric[], '[]'::jsonb, '[{"key":"a","label":"Side","unit":"mm","std":[15,20,25,32,40,50,60,72,80,100,120,150],"min":10,"max":400},{"key":"t","label":"Wall thickness","unit":"mm","std":[1,1.2,1.6,2,2.6,3.2,4,4.8,6],"min":0.8,"max":16}]'::jsonb, 'Square hollow sections (SHS) for frames, gates, trusses and machine bases.', 12),
('rect-hollow', 'Rectangular Hollow Section', 'pipe', 'rect_tube', 'piece', 'welded', 8, array[6000]::numeric[], '[]'::jsonb, '[{"key":"a","label":"Width","unit":"mm","std":[40,50,60,80,100,120,150,200],"min":10,"max":400},{"key":"b","label":"Height","unit":"mm","std":[20,25,30,40,50,60,80,100],"min":10,"max":400},{"key":"t","label":"Wall thickness","unit":"mm","std":[1.2,1.6,2,2.6,3.2,4,4.8,6],"min":0.8,"max":16}]'::jsonb, 'Rectangular hollow sections (RHS) for frames, purlins and conveyors.', 13),
('equal-angle', 'Equal Angle', 'section', 'equal_angle', 'piece', 'section', 0, array[6000]::numeric[], '[]'::jsonb, '[{"key":"a","label":"Leg","unit":"mm","std":[20,25,30,35,40,45,50,65,75,90,100,150],"min":10,"max":250},{"key":"t","label":"Thickness","unit":"mm","std":[3,4,5,6,8,10,12],"min":2,"max":30}]'::jsonb, 'Equal-leg L angles for bracing, supports, frames and edge protection.', 14),
('t-section', 'T Section', 'section', 't_section', 'piece', 'section', 5, array[6000]::numeric[], '[]'::jsonb, '[{"key":"b","label":"Flange width","unit":"mm","std":[20,25,30,40,50,60],"min":10,"max":200},{"key":"h","label":"Height","unit":"mm","std":[20,25,30,40,50,60],"min":10,"max":200},{"key":"t","label":"Thickness","unit":"mm","std":[3,4,5,6,8],"min":2,"max":20}]'::jsonb, 'T sections for glazing bars, stiffeners and light structural members.', 15),
('ismc-channel', 'C Channel (ISMC)', 'section', 'ismc', 'piece', 'section', 0, array[6000]::numeric[], '[]'::jsonb, '[{"key":"size","label":"ISMC size (depth)","unit":"mm","std":[75,100,125,150,175,200,225,250,300,350,400],"min":75,"max":400}]'::jsonb, 'Indian Standard Medium-weight Channels to IS 808, priced on nominal kg/m.', 16),
('wire-rod', 'Wire / Wire Rod', 'wire', 'wire', 'kg', 'wire', 5, '{}'::numeric[], '[]'::jsonb, '[{"key":"d","label":"Diameter","unit":"mm","std":[1,1.6,2,2.5,3,4,5,5.5,6,8,10,12],"min":0.2,"max":20}]'::jsonb, 'Wire and wire rod in coils, sold by weight, for springs, fasteners and forming.', 17)
on conflict (slug) do update set name = excluded.name, family = excluded.family, formula = excluded.formula,
  sell_by = excluded.sell_by, hsn_key = excluded.hsn_key, std_lengths = excluded.std_lengths,
  std_sheet_sizes = excluded.std_sheet_sizes, dims = excluded.dims, description = excluded.description,
  sort_order = excluded.sort_order;

insert into public.rm_materials (slug, name, short_name, density, hsn_codes, gst_rate, description, sort_order) values
('stainless-steel', 'Stainless Steel', 'SS', 7.93, '{"bar":"7222","flat":"7219","section":"7222","seamless":"7304","welded":"7306","wire":"7221"}'::jsonb, 18, 'Corrosion-resistant iron–chromium(–nickel) steels. Austenitic grades (304, 316) are non-magnetic and weldable; martensitic grades (410, 420, 440C) harden; duplex grades combine strength with chloride resistance.', 1),
('mild-steel', 'Mild Steel', 'MS', 7.85, '{"bar":"7214","flat":"7208","section":"7216","seamless":"7304","welded":"7306","wire":"7213"}'::jsonb, 18, 'Low-carbon structural steel — weldable, easy to fabricate and the most economical choice for frames, sections and plates.', 2),
('carbon-steel', 'Carbon Steel', 'CS', 7.85, '{"bar":"7214","flat":"7208","section":"7216","seamless":"7304","welded":"7306","wire":"7213"}'::jsonb, 18, 'Medium-carbon engineering steels for shafts, gears and machined parts; can be hardened and tempered.', 3),
('alloy-steel', 'Alloy Steel', 'AS', 7.85, '{"bar":"7228","flat":"7225","section":"7228","seamless":"7304","welded":"7306","wire":"7227"}'::jsonb, 18, 'Chromium, nickel and molybdenum alloyed steels (EN series) for high-strength, tough or case-hardened components.', 4),
('tool-steel', 'Tool Steel', 'TS', 7.75, '{"bar":"7228","flat":"7225","section":"7228","seamless":"7304","welded":"7306","wire":"7227"}'::jsonb, 18, 'High-carbon alloy steels for dies, punches, moulds and cutting tools; supplied annealed for machining.', 5),
('spring-steel', 'Spring Steel', 'SPR', 7.85, '{"bar":"7228","flat":"7225","section":"7228","seamless":"7304","welded":"7306","wire":"7227"}'::jsonb, 18, 'High-carbon and chrome-vanadium steels that return to shape after load — springs, clips, blades.', 6),
('aluminium', 'Aluminium', 'Al', 2.7, '{"bar":"7604","flat":"7606","section":"7604","seamless":"7608","welded":"7608","wire":"7605"}'::jsonb, 18, 'Light (about one-third the weight of steel), corrosion-resistant and highly machinable. Series 5xxx for marine/sheet work, 6xxx for extrusions and general machining, 2xxx/7xxx for high strength.', 7),
('copper', 'Copper', 'Cu', 8.94, '{"bar":"7407","flat":"7409","section":"7407","seamless":"7411","welded":"7411","wire":"7408"}'::jsonb, 18, 'Best-in-class electrical and thermal conductivity — busbars, earthing, heat exchangers and plumbing.', 8),
('brass', 'Brass', 'Brass', 8.5, '{"bar":"7407","flat":"7409","section":"7407","seamless":"7411","welded":"7411","wire":"7408"}'::jsonb, 18, 'Copper–zinc alloys: free-machining for turned parts and fittings, ductile grades for deep drawing and tubes.', 9),
('bronze', 'Bronze', 'Bronze', 8.8, '{"bar":"7407","flat":"7409","section":"7407","seamless":"7411","welded":"7411","wire":"7408"}'::jsonb, 18, 'Copper–tin and copper–aluminium alloys for bushes, bearings, gears and marine hardware.', 10),
('nickel-alloys', 'Nickel Alloys', 'Ni', 8.4, '{"bar":"7505","flat":"7506","section":"7505","seamless":"7507","welded":"7507","wire":"7505"}'::jsonb, 18, 'Nickel-based superalloys for extreme corrosion and temperature — chemical plant, oil & gas, aerospace.', 11),
('titanium', 'Titanium', 'Ti', 4.51, '{"bar":"8108","flat":"8108","section":"8108","seamless":"8108","welded":"8108","wire":"8108"}'::jsonb, 18, 'Very high strength-to-weight and outstanding corrosion resistance — aerospace, medical and chemical service.', 12)
on conflict (slug) do update set name = excluded.name, short_name = excluded.short_name, density = excluded.density,
  hsn_codes = excluded.hsn_codes, description = excluded.description, sort_order = excluded.sort_order;

insert into public.rm_shape_materials (shape_id, material_id)
select s.id, m.id from (values
('stainless-steel', 'round-bar'),
('stainless-steel', 'square-bar'),
('stainless-steel', 'hex-bar'),
('stainless-steel', 'flat-bar'),
('stainless-steel', 'sheet'),
('stainless-steel', 'plate'),
('stainless-steel', 'chequered-plate'),
('stainless-steel', 'perforated-sheet'),
('stainless-steel', 'coil'),
('stainless-steel', 'seamless-pipe'),
('stainless-steel', 'erw-pipe'),
('stainless-steel', 'square-hollow'),
('stainless-steel', 'rect-hollow'),
('stainless-steel', 'equal-angle'),
('stainless-steel', 'wire-rod'),
('mild-steel', 'round-bar'),
('mild-steel', 'square-bar'),
('mild-steel', 'flat-bar'),
('mild-steel', 'sheet'),
('mild-steel', 'plate'),
('mild-steel', 'chequered-plate'),
('mild-steel', 'perforated-sheet'),
('mild-steel', 'coil'),
('mild-steel', 'erw-pipe'),
('mild-steel', 'square-hollow'),
('mild-steel', 'rect-hollow'),
('mild-steel', 'equal-angle'),
('mild-steel', 't-section'),
('mild-steel', 'ismc-channel'),
('mild-steel', 'wire-rod'),
('carbon-steel', 'round-bar'),
('carbon-steel', 'square-bar'),
('carbon-steel', 'hex-bar'),
('carbon-steel', 'flat-bar'),
('carbon-steel', 'plate'),
('carbon-steel', 'seamless-pipe'),
('alloy-steel', 'round-bar'),
('alloy-steel', 'square-bar'),
('alloy-steel', 'hex-bar'),
('alloy-steel', 'flat-bar'),
('alloy-steel', 'plate'),
('tool-steel', 'round-bar'),
('tool-steel', 'square-bar'),
('tool-steel', 'flat-bar'),
('tool-steel', 'plate'),
('spring-steel', 'round-bar'),
('spring-steel', 'flat-bar'),
('spring-steel', 'coil'),
('spring-steel', 'wire-rod'),
('aluminium', 'round-bar'),
('aluminium', 'square-bar'),
('aluminium', 'hex-bar'),
('aluminium', 'flat-bar'),
('aluminium', 'sheet'),
('aluminium', 'plate'),
('aluminium', 'chequered-plate'),
('aluminium', 'perforated-sheet'),
('aluminium', 'coil'),
('aluminium', 'seamless-pipe'),
('aluminium', 'square-hollow'),
('aluminium', 'rect-hollow'),
('aluminium', 'equal-angle'),
('aluminium', 't-section'),
('copper', 'round-bar'),
('copper', 'square-bar'),
('copper', 'flat-bar'),
('copper', 'sheet'),
('copper', 'plate'),
('copper', 'coil'),
('copper', 'seamless-pipe'),
('copper', 'wire-rod'),
('brass', 'round-bar'),
('brass', 'square-bar'),
('brass', 'hex-bar'),
('brass', 'flat-bar'),
('brass', 'sheet'),
('brass', 'plate'),
('brass', 'seamless-pipe'),
('bronze', 'round-bar'),
('nickel-alloys', 'round-bar'),
('nickel-alloys', 'sheet'),
('nickel-alloys', 'plate'),
('nickel-alloys', 'seamless-pipe'),
('titanium', 'round-bar'),
('titanium', 'sheet'),
('titanium', 'plate'),
('titanium', 'seamless-pipe')
) v(material, shape)
join public.rm_materials m on m.slug = v.material
join public.rm_shapes s on s.slug = v.shape
on conflict do nothing;

create temporary table _rm_seed_grades (material text, slug text, name text, equivalents text,
  description text, applications text, density numeric, shape_slugs text[], sort_order int, rate numeric) on commit drop;
insert into _rm_seed_grades values
('stainless-steel', 'ss-201', 'SS 201', 'UNS S20100 · EN 1.4372', 'Low-nickel austenitic (Cr-Mn-Ni) grade; economical for indoor, low-corrosion use.', 'Kitchenware, furniture, decorative tube', 7.8::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar', 'sheet', 'plate', 'coil', 'erw-pipe', 'square-hollow', 'rect-hollow']::text[], 1, 150::numeric),
('stainless-steel', 'ss-202', 'SS 202', 'UNS S20200', 'Manganese-bearing austenitic grade, a lower-cost alternative to 304 for mild environments.', 'Railings, utensils, architectural trim', 7.8::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar', 'sheet', 'plate', 'coil', 'erw-pipe', 'square-hollow', 'rect-hollow', 'equal-angle']::text[], 2, 160::numeric),
('stainless-steel', 'ss-303', 'SS 303', 'UNS S30300 · EN 1.4305', 'Free-machining austenitic grade (added sulphur); best for high-volume turning, not for welding.', 'Nuts, bolts, shafts, fittings', 8.0::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar']::text[], 3, 260::numeric),
('stainless-steel', 'ss-304', 'SS 304', 'UNS S30400 · EN 1.4301 · AISI 304', 'The standard 18/8 austenitic stainless — good corrosion resistance, food-grade, weldable and formable.', 'Food & dairy equipment, tanks, architecture', 7.93::numeric, null, 4, 230::numeric),
('stainless-steel', 'ss-304l', 'SS 304L', 'UNS S30403 · EN 1.4307', 'Low-carbon 304 that avoids weld-zone sensitisation; preferred for heavy welded fabrication.', 'Welded tanks, pipework, pressure parts', 7.93::numeric, null, 5, 240::numeric),
('stainless-steel', 'ss-310s', 'SS 310S', 'UNS S31008 · EN 1.4845', 'High Cr-Ni heat-resisting grade, oxidation resistant to about 1,100 °C.', 'Furnace parts, burners, heat exchangers', 7.9::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar', 'sheet', 'plate', 'seamless-pipe']::text[], 6, 420::numeric),
('stainless-steel', 'ss-316', 'SS 316', 'UNS S31600 · EN 1.4401 · AISI 316', 'Molybdenum-bearing austenitic grade with better pitting and chloride resistance than 304.', 'Marine, pharma, chemical process equipment', 8.0::numeric, null, 7, 330::numeric),
('stainless-steel', 'ss-316l', 'SS 316L', 'UNS S31603 · EN 1.4404', 'Low-carbon 316 for welded assemblies in corrosive service.', 'Pharma piping, marine fittings, valves', 8.0::numeric, null, 8, 340::numeric),
('stainless-steel', 'ss-316ti', 'SS 316Ti', 'UNS S31635 · EN 1.4571', 'Titanium-stabilised 316 for sustained elevated-temperature service.', 'Exhaust systems, heat exchangers', 8.0::numeric, array['round-bar', 'sheet', 'plate', 'seamless-pipe']::text[], 9, 380::numeric),
('stainless-steel', 'ss-317l', 'SS 317L', 'UNS S31703 · EN 1.4438', 'Higher-molybdenum austenitic grade for aggressive chemical environments.', 'Pulp & paper, flue-gas desulphurisation', 8.0::numeric, array['round-bar', 'sheet', 'plate', 'seamless-pipe']::text[], 10, 420::numeric),
('stainless-steel', 'ss-321', 'SS 321', 'UNS S32100 · EN 1.4541', 'Titanium-stabilised 18/8 for 425–900 °C service without intergranular corrosion.', 'Exhaust manifolds, expansion joints', 7.9::numeric, array['round-bar', 'sheet', 'plate', 'seamless-pipe', 'erw-pipe']::text[], 11, 300::numeric),
('stainless-steel', 'ss-347', 'SS 347', 'UNS S34700 · EN 1.4550', 'Niobium-stabilised austenitic grade for high-temperature welded service.', 'Aircraft exhausts, boiler shells', 7.96::numeric, array['round-bar', 'sheet', 'plate', 'seamless-pipe']::text[], 12, 360::numeric),
('stainless-steel', 'ss-409', 'SS 409', 'UNS S40900 · EN 1.4512', 'Ferritic 11% Cr grade; economical, moderate corrosion resistance.', 'Automotive exhausts, mufflers', 7.7::numeric, array['sheet', 'coil', 'erw-pipe']::text[], 13, 140::numeric),
('stainless-steel', 'ss-410', 'SS 410', 'UNS S41000 · EN 1.4006', 'Hardenable martensitic grade with moderate corrosion resistance.', 'Pump shafts, valve parts, cutlery', 7.75::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar', 'sheet', 'plate']::text[], 14, 190::numeric),
('stainless-steel', 'ss-420', 'SS 420', 'UNS S42000 · EN 1.4021 / 1.4028', 'Higher-carbon martensitic grade that reaches greater hardness than 410. (420J2 is the Japanese sheet variant.)', 'Surgical instruments, blades, moulds', 7.75::numeric, array['round-bar', 'flat-bar', 'sheet', 'plate']::text[], 15, 210::numeric),
('stainless-steel', 'ss-430', 'SS 430', 'UNS S43000 · EN 1.4016', 'Ferritic, magnetic 17% Cr grade with good formability for indoor use.', 'Appliance panels, trim, sinks', 7.7::numeric, array['round-bar', 'sheet', 'coil']::text[], 16, 150::numeric),
('stainless-steel', 'ss-440c', 'SS 440C', 'UNS S44004 · EN 1.4125', 'High-carbon martensitic grade with the highest hardness of the stainless family.', 'Bearings, valve seats, knives', 7.65::numeric, array['round-bar']::text[], 17, 450::numeric),
('stainless-steel', 'ss-17-4ph', '17-4 PH (SS 630)', 'UNS S17400 · EN 1.4542', 'Precipitation-hardening grade combining high strength with 304-level corrosion resistance.', 'Aerospace fittings, pump shafts, gears', 7.8::numeric, array['round-bar', 'flat-bar', 'plate']::text[], 18, 600::numeric),
('stainless-steel', 'duplex-2205', 'Duplex 2205', 'UNS S32205 / S31803 · EN 1.4462', 'Austenitic-ferritic duplex with about twice the strength of 316 and excellent chloride stress-corrosion resistance.', 'Oil & gas, desalination, chemical tanks', 7.8::numeric, array['round-bar', 'sheet', 'plate', 'seamless-pipe']::text[], 19, 550::numeric),
('stainless-steel', 'super-duplex-2507', 'Super Duplex 2507', 'UNS S32750 · EN 1.4410', 'Higher-alloy duplex for seawater and severe chloride service.', 'Offshore, sea-water systems', 7.8::numeric, array['round-bar', 'plate', 'seamless-pipe']::text[], 20, 850::numeric),
('stainless-steel', 'ss-904l', 'SS 904L', 'UNS N08904 · EN 1.4539', 'Super-austenitic grade with high Ni-Mo-Cu for sulphuric acid and chloride environments.', 'Acid plants, heat exchangers', 7.95::numeric, array['round-bar', 'sheet', 'plate', 'seamless-pipe']::text[], 21, 1300::numeric),
('stainless-steel', 'smo-254', '254 SMO', 'UNS S31254 · EN 1.4547', '6-Mo super-austenitic stainless for sea water and bleach plants.', 'Sea-water piping, pulp bleaching', 8.0::numeric, array['round-bar', 'sheet', 'plate', 'seamless-pipe']::text[], 22, 1400::numeric),
('mild-steel', 'is-2062-e250', 'IS 2062 E250', 'Fe 410 · ≈ ASTM A36 / S235', 'Standard Indian structural steel (yield 250 MPa); weldable and the default for fabrication.', 'Structures, frames, base plates', null::numeric, array['round-bar', 'square-bar', 'flat-bar', 'sheet', 'plate', 'chequered-plate', 'coil', 'equal-angle', 't-section', 'ismc-channel']::text[], 1, 62::numeric),
('mild-steel', 'is-2062-e350', 'IS 2062 E350', 'Fe 490 · ≈ S355', 'Higher-strength structural steel (yield 350 MPa) for lighter, stronger members.', 'Heavy structures, cranes, bridges', null::numeric, array['round-bar', 'flat-bar', 'plate', 'equal-angle', 'ismc-channel']::text[], 2, 68::numeric),
('mild-steel', 'is-513', 'IS 513 (CR sheet)', 'CR1–CR4 · ≈ DC01–DC04', 'Cold-rolled low-carbon sheet with good surface and formability.', 'Panels, enclosures, pressed parts', null::numeric, array['sheet', 'coil', 'perforated-sheet']::text[], 3, 70::numeric),
('mild-steel', 'is-1079', 'IS 1079 (HR sheet)', 'HR1–HR4 · ≈ DD11–DD13', 'Hot-rolled low-carbon sheet and coil for general forming.', 'Brackets, tanks, general fabrication', null::numeric, array['sheet', 'coil']::text[], 4, 64::numeric),
('mild-steel', 'is-1239', 'IS 1239 (ERW pipe)', 'Light / Medium / Heavy class', 'Welded mild steel tubes for water, gas and structural use.', 'Plumbing, scaffolding, railings', null::numeric, array['erw-pipe']::text[], 5, 72::numeric),
('mild-steel', 'is-4923', 'IS 4923 YSt 310', 'Hollow structural sections', 'Cold-formed hollow sections (yield 310 MPa) for tubular structures.', 'Gates, trusses, frames', null::numeric, array['square-hollow', 'rect-hollow']::text[], 6, 70::numeric),
('mild-steel', 'sae-1008', 'SAE 1008 wire rod', '≈ C10 · EN 1.0204', 'Low-carbon wire rod for drawing and cold heading.', 'Nails, wire mesh, fasteners', null::numeric, array['wire-rod']::text[], 7, 66::numeric),
('carbon-steel', 'en8', 'EN8 (080M40)', '≈ C40 · AISI 1040', 'Unalloyed medium-carbon steel with good tensile strength; supplied normalised or bright.', 'Shafts, studs, bolts, gears', null::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar', 'plate']::text[], 1, 75::numeric),
('carbon-steel', 'en9', 'EN9 (070M55)', '≈ C55 · AISI 1055', 'Higher-carbon steel for wear resistance; can be flame or induction hardened.', 'Sprockets, cams, cutting tools', null::numeric, array['round-bar', 'flat-bar', 'plate']::text[], 2, 80::numeric),
('carbon-steel', 'c45', 'C45', 'EN 1.0503 · ≈ AISI 1045', 'European medium-carbon grade widely used for machined parts.', 'Axles, spindles, pins', null::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar', 'plate']::text[], 3, 78::numeric),
('carbon-steel', 'aisi-1018', 'AISI 1018', '≈ C15 · EN 1.0401', 'Low-carbon bright bar with excellent machinability and weldability; case-hardenable.', 'Pins, spacers, machined parts', null::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar']::text[], 4, 72::numeric),
('carbon-steel', 'astm-a105', 'ASTM A105', 'Carbon steel forging grade', 'Forged carbon steel for pressure-containing parts at ambient and higher temperatures.', 'Flanges, fittings, valve bodies', null::numeric, array['round-bar']::text[], 5, 85::numeric),
('carbon-steel', 'astm-a106-b', 'ASTM A106 Gr. B', '≈ API 5L Gr. B', 'Seamless carbon steel pipe for high-temperature service.', 'Steam lines, refinery piping', null::numeric, array['seamless-pipe']::text[], 6, 95::numeric),
('alloy-steel', 'en19', 'EN19 (709M40)', '≈ 42CrMo4 · AISI 4140', 'Chromium-molybdenum steel with high tensile strength and toughness; hardenable.', 'Shafts, gears, high-tensile bolts', null::numeric, null, 1, 110::numeric),
('alloy-steel', 'en24', 'EN24 (817M40)', '≈ 34CrNiMo6 · AISI 4340', 'Nickel-chromium-molybdenum steel for heavily stressed components.', 'Crankshafts, axles, heavy-duty gears', null::numeric, null, 2, 125::numeric),
('alloy-steel', 'en31', 'EN31 (535A99)', '≈ 100Cr6 · AISI 52100', 'High-carbon chromium bearing steel; very hard and wear resistant after hardening.', 'Bearings, rollers, press tools', null::numeric, array['round-bar', 'flat-bar', 'plate']::text[], 3, 115::numeric),
('alloy-steel', 'en353', 'EN353', '≈ 15NiCr13 (case-hardening)', 'Nickel-chromium case-hardening steel with a tough core.', 'Gears, pinions, cam shafts', null::numeric, array['round-bar', 'flat-bar']::text[], 4, 110::numeric),
('alloy-steel', 'en36', 'EN36 (655M13)', '≈ 14NiCr14', 'High-nickel case-hardening steel for highly stressed carburised parts.', 'Aircraft gears, heavy-duty shafts', null::numeric, array['round-bar', 'flat-bar']::text[], 5, 130::numeric),
('alloy-steel', '16mncr5', '16MnCr5', 'EN 1.7131 · ≈ AISI 5115', 'Manganese-chromium case-hardening steel.', 'Gears, shafts, piston pins', null::numeric, array['round-bar', 'square-bar', 'flat-bar']::text[], 6, 100::numeric),
('alloy-steel', '20mncr5', '20MnCr5', 'EN 1.7147 · ≈ AISI 5120', 'Case-hardening steel with a slightly stronger core than 16MnCr5.', 'Transmission gears, spindles', null::numeric, array['round-bar', 'square-bar', 'flat-bar']::text[], 7, 105::numeric),
('tool-steel', 'd2', 'D2', 'EN 1.2379 · X153CrMoV12', 'High-carbon high-chromium cold-work steel with excellent wear resistance.', 'Blanking dies, punches, shear blades', 7.7::numeric, null, 1, 450::numeric),
('tool-steel', 'd3', 'D3', 'EN 1.2080 · X210Cr12', 'High-carbon chromium cold-work steel for long production runs.', 'Drawing dies, forming tools', 7.7::numeric, null, 2, 380::numeric),
('tool-steel', 'o1-ohns', 'O1 / OHNS', 'EN 1.2510 · 100MnCrW4', 'Oil-hardening non-shrinking tool steel; easy to heat-treat with low distortion.', 'Gauges, punches, small dies', 7.8::numeric, null, 3, 300::numeric),
('tool-steel', 'h13', 'H13', 'EN 1.2344 · X40CrMoV5-1', 'Chromium hot-work steel with high toughness and thermal-fatigue resistance.', 'Die-casting dies, extrusion tooling', 7.8::numeric, null, 4, 450::numeric),
('tool-steel', 'm2', 'M2 (HSS)', 'EN 1.3343 · HS6-5-2', 'Molybdenum-tungsten high-speed steel that keeps hardness at cutting temperatures.', 'Drills, taps, tool bits', 8.16::numeric, array['round-bar', 'flat-bar']::text[], 5, 1200::numeric),
('spring-steel', 'en42j', 'EN42J (080A78)', '≈ C75 / C80', 'High-carbon spring steel in strip and flat form.', 'Flat springs, clips, washers', null::numeric, array['flat-bar', 'coil']::text[], 1, 110::numeric),
('spring-steel', 'en47', 'EN47 (735A51)', '≈ 50CrV4 · AISI 6150', 'Chromium-vanadium spring steel with good fatigue strength.', 'Leaf springs, torsion bars', null::numeric, array['round-bar', 'flat-bar']::text[], 2, 120::numeric),
('spring-steel', 'is-4454-sw', 'IS 4454 spring wire', 'Grade SW / DH', 'Patented cold-drawn spring wire.', 'Coil springs, wire forms', null::numeric, array['wire-rod']::text[], 3, 130::numeric),
('aluminium', 'al-1050', '1050', 'Al 99.5 · IS 19000', 'Commercially pure aluminium; very formable and conductive, low strength.', 'Reflectors, chemical tanks, name plates', 2.71::numeric, array['sheet', 'plate', 'coil']::text[], 1, 290::numeric),
('aluminium', 'al-1100', '1100', 'Al 99.0 · IS 19500', 'Commercially pure aluminium with slightly higher strength than 1050.', 'Cookware, fins, spun parts', 2.71::numeric, array['sheet', 'coil', 'perforated-sheet']::text[], 2, 295::numeric),
('aluminium', 'al-2011', '2011', 'AlCu6BiPb · EN AW-2011', 'Free-machining copper alloy for automatic lathe work; not weldable.', 'Screw-machine parts, fittings', 2.83::numeric, array['round-bar', 'hex-bar']::text[], 3, 450::numeric),
('aluminium', 'al-2014', '2014 (HE15)', 'AlCu4SiMg · EN AW-2014', 'High-strength heat-treatable copper alloy.', 'Aircraft fittings, truck frames', 2.8::numeric, array['round-bar', 'flat-bar', 'plate']::text[], 4, 520::numeric),
('aluminium', 'al-2024', '2024', 'AlCu4Mg1 · EN AW-2024', 'High-strength aerospace alloy with good fatigue resistance.', 'Aircraft structures, rivets', 2.78::numeric, array['round-bar', 'flat-bar', 'sheet', 'plate']::text[], 5, 700::numeric),
('aluminium', 'al-3003', '3003', 'AlMn1Cu · EN AW-3003', 'Manganese alloy, stronger than pure aluminium and very workable.', 'Roofing, tanks, heat exchangers', 2.73::numeric, array['sheet', 'coil', 'chequered-plate', 'perforated-sheet']::text[], 6, 300::numeric),
('aluminium', 'al-4032', '4032', 'AlSi12.5MgCuNi', 'Silicon alloy with low thermal expansion and good wear resistance.', 'Pistons, compressor parts', 2.68::numeric, array['round-bar']::text[], 7, 500::numeric),
('aluminium', 'al-5052', '5052', 'AlMg2.5 · EN AW-5052', 'Magnesium alloy with good fatigue strength and sea-water resistance.', 'Marine panels, fuel tanks, enclosures', 2.68::numeric, array['sheet', 'plate', 'coil', 'chequered-plate', 'perforated-sheet']::text[], 8, 340::numeric),
('aluminium', 'al-5083', '5083', 'AlMg4.5Mn0.7 · EN AW-5083', 'Highest-strength non-heat-treatable alloy; excellent in sea water and weldable.', 'Ship hulls, cryogenic tanks', 2.66::numeric, array['sheet', 'plate']::text[], 9, 380::numeric),
('aluminium', 'al-5754', '5754', 'AlMg3 · EN AW-5754', 'Magnesium alloy with high corrosion resistance and good formability.', 'Treadplate, vehicle bodies', 2.67::numeric, array['sheet', 'plate', 'chequered-plate']::text[], 10, 350::numeric),
('aluminium', 'al-6061', '6061 (HE20)', 'AlMg1SiCu · EN AW-6061', 'Versatile heat-treatable alloy — good strength, machinability and weldability (T6).', 'Machined parts, fixtures, frames', 2.7::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar', 'sheet', 'plate', 'seamless-pipe']::text[], 11, 330::numeric),
('aluminium', 'al-6063', '6063 (HE9)', 'AlMg0.7Si · EN AW-6063', 'The extrusion alloy — excellent surface finish and anodising response.', 'Window frames, profiles, tubes', 2.69::numeric, array['round-bar', 'flat-bar', 'seamless-pipe', 'square-hollow', 'rect-hollow', 'equal-angle', 't-section']::text[], 12, 300::numeric),
('aluminium', 'al-6082', '6082 (HE30)', 'AlSi1MgMn · EN AW-6082', 'Structural heat-treatable alloy, the highest-strength 6xxx.', 'Structural members, cranes, bridges', 2.7::numeric, array['round-bar', 'square-bar', 'hex-bar', 'flat-bar', 'plate', 'equal-angle']::text[], 13, 340::numeric),
('aluminium', 'al-7075', '7075', 'AlZn5.5MgCu · EN AW-7075', 'Zinc alloy with the strength of many steels; aerospace and tooling grade.', 'Aircraft parts, moulds, high-stress fittings', 2.81::numeric, array['round-bar', 'square-bar', 'flat-bar', 'sheet', 'plate']::text[], 14, 650::numeric),
('copper', 'cu-etp', 'ETP Copper', 'Cu-ETP · C11000 · EN CW004A', 'Electrolytic tough-pitch copper, ≥ 99.90% Cu, for electrical conductors.', 'Busbars, earthing, transformer windings', 8.94::numeric, array['round-bar', 'square-bar', 'flat-bar', 'sheet', 'plate', 'coil', 'wire-rod']::text[], 1, 950::numeric),
('copper', 'cu-dhp', 'DHP Copper', 'Cu-DHP · C12200 · EN CW024A', 'Phosphorus-deoxidised copper that brazes and welds well.', 'Plumbing, refrigeration tubes, heat exchangers', 8.94::numeric, array['sheet', 'coil', 'seamless-pipe']::text[], 2, 930::numeric),
('brass', 'brass-is-319', 'Free-cutting Brass (IS 319)', 'CuZn39Pb3 · C38500 · CW614N', 'Leaded brass with the best machinability of all copper alloys.', 'Turned parts, valves, fittings', 8.47::numeric, array['round-bar', 'square-bar', 'hex-bar']::text[], 1, 620::numeric),
('brass', 'brass-cuzn30', 'CuZn30 (70/30 brass)', 'C26000 · CW505L', 'Cartridge brass — excellent cold ductility for deep drawing.', 'Cartridge cases, radiator cores', 8.53::numeric, array['sheet', 'flat-bar', 'seamless-pipe']::text[], 2, 650::numeric),
('brass', 'brass-cuzn37', 'CuZn37 (63/37 brass)', 'C27200 · CW508L', 'General-purpose brass for pressing and tube work.', 'Tubes, pressed parts, decorative', 8.44::numeric, array['sheet', 'plate', 'flat-bar', 'seamless-pipe']::text[], 3, 630::numeric),
('brass', 'brass-cuzn40', 'CuZn40 (Muntz metal)', 'C28000 · CW509L', '60/40 brass, strong and hot-workable.', 'Condenser plates, fasteners, architectural', 8.39::numeric, array['round-bar', 'flat-bar', 'plate']::text[], 4, 600::numeric),
('bronze', 'pb1', 'Phosphor Bronze PB1', 'BS 1400 PB1 · ≈ C90700', 'Cast/continuous-cast tin bronze with high wear resistance.', 'Bearings, worm wheels, gears', 8.8::numeric, null, 1, 1100::numeric),
('bronze', 'pb2', 'Phosphor Bronze PB2', 'BS 1400 PB2 · ≈ C90800', 'Higher-tin cast bronze for heavily loaded bearings and gears.', 'Heavy-duty bushes, gears', 8.7::numeric, null, 2, 1150::numeric),
('bronze', 'lg2', 'Gunmetal LG2', 'BS 1400 LG2 · ≈ C83600', 'Leaded tin bronze with good castability and pressure tightness.', 'Pump bodies, valves, bushes', 8.8::numeric, null, 3, 900::numeric),
('bronze', 'ab2', 'Aluminium Bronze AB2', 'BS 1400 AB2 · ≈ C95800', 'Nickel-aluminium bronze with high strength and sea-water resistance.', 'Marine propellers, pump parts', 7.64::numeric, null, 4, 1000::numeric),
('nickel-alloys', 'alloy-20', 'Alloy 20', 'UNS N08020 · EN 2.4660', 'Ni-Fe-Cr alloy designed for sulphuric acid service.', 'Acid pickling, chemical process', 8.08::numeric, null, 1, 2600::numeric),
('nickel-alloys', 'hastelloy-c22', 'Hastelloy C-22', 'UNS N06022 · EN 2.4602', 'Ni-Cr-Mo-W alloy resisting oxidising and reducing media.', 'Pharma reactors, scrubbers', 8.69::numeric, null, 2, 5200::numeric),
('nickel-alloys', 'hastelloy-c276', 'Hastelloy C-276', 'UNS N10276 · EN 2.4819', 'Ni-Mo-Cr alloy with outstanding resistance to severe corrosion.', 'Flue-gas systems, chemical reactors', 8.89::numeric, null, 3, 5500::numeric),
('nickel-alloys', 'incoloy-800', 'Incoloy 800', 'UNS N08800 · EN 1.4876', 'Fe-Ni-Cr alloy for high-temperature strength and oxidation resistance.', 'Furnace components, heat exchangers', 7.94::numeric, null, 4, 2200::numeric),
('nickel-alloys', 'incoloy-825', 'Incoloy 825', 'UNS N08825 · EN 2.4858', 'Ni-Fe-Cr alloy with Mo and Cu for acid and chloride environments.', 'Oil & gas tubing, acid production', 8.14::numeric, null, 5, 3000::numeric),
('nickel-alloys', 'inconel-600', 'Inconel 600', 'UNS N06600 · EN 2.4816', 'Ni-Cr alloy for high-temperature and corrosive service.', 'Furnace parts, heat-treat fixtures', 8.47::numeric, null, 6, 3500::numeric),
('nickel-alloys', 'inconel-601', 'Inconel 601', 'UNS N06601 · EN 2.4851', 'Ni-Cr-Al alloy with exceptional oxidation resistance.', 'Radiant tubes, combustion chambers', 8.11::numeric, null, 7, 3600::numeric),
('nickel-alloys', 'inconel-625', 'Inconel 625', 'UNS N06625 · EN 2.4856', 'Ni-Cr-Mo-Nb alloy with high strength and superb corrosion resistance.', 'Aerospace ducting, sea-water parts', 8.44::numeric, null, 8, 4500::numeric),
('nickel-alloys', 'inconel-718', 'Inconel 718', 'UNS N07718 · EN 2.4668', 'Precipitation-hardening superalloy for high strength to 700 °C.', 'Jet-engine parts, fasteners', 8.19::numeric, null, 9, 5000::numeric),
('nickel-alloys', 'monel-400', 'Monel 400', 'UNS N04400 · EN 2.4360', 'Ni-Cu alloy with excellent resistance to sea water and hydrofluoric acid.', 'Marine fittings, pump shafts', 8.8::numeric, null, 10, 3000::numeric),
('nickel-alloys', 'nickel-200', 'Nickel 200', 'UNS N02200 · EN 2.4066', 'Commercially pure wrought nickel for caustic environments.', 'Caustic handling, electronics', 8.89::numeric, null, 11, 2800::numeric),
('titanium', 'ti-grade-2', 'Titanium Grade 2', 'UNS R50400 · CP titanium', 'Commercially pure titanium — the most widely used grade for corrosion service.', 'Heat exchangers, chemical plant, marine', 4.51::numeric, null, 1, 2800::numeric),
('titanium', 'ti-grade-5', 'Titanium Grade 5 (Ti-6Al-4V)', 'UNS R56400 · EN 3.7165', 'Alpha-beta alloy with high strength-to-weight; the workhorse aerospace and implant grade.', 'Aerospace, medical implants, motorsport', 4.43::numeric, null, 2, 4200::numeric);

insert into public.rm_grades (material_id, slug, name, equivalents, description, applications, density, shape_slugs, sort_order)
select m.id, g.slug, g.name, g.equivalents, g.description, g.applications, g.density, g.shape_slugs, g.sort_order
from _rm_seed_grades g join public.rm_materials m on m.slug = g.material
on conflict (material_id, slug) do update set name = excluded.name, equivalents = excluded.equivalents,
  description = excluded.description, applications = excluded.applications, density = excluded.density,
  shape_slugs = excluded.shape_slugs, sort_order = excluded.sort_order;

insert into public.rm_rates (grade_id, shape_id, rate_per_kg)
select rg.id, null, g.rate
from _rm_seed_grades g
join public.rm_materials m on m.slug = g.material
join public.rm_grades rg on rg.material_id = m.id and rg.slug = g.slug
where not exists (select 1 from public.rm_rates r where r.grade_id = rg.id and r.shape_id is null);

drop table if exists _rm_seed_grades;
